### ISSUE TITLE
Question: Is it possible to mark any component to be processed by static css extractor?

### ISSUE THREAD

**Issue by ex3ndr** [jsxstyle/jsxstyle#126]
Right now i am wondering if using this library will allow me to build my own wrappers around jsxstyle's components that fits my requirements better. They are mostly simple wrappers with additional/preprocessed props of original one.

Is it doable?

**Comment by meyer** [comment]
@ex3ndr I’ve been thinking about this for a while now. I personally only ever use `Row`, `Col`, and `Block`, and sometimes I feel like the primitives are a bit _too_ primitive.

Long story short, I think this should be doable and I think it’s a good direction to go with jsxstyle, but it’ll need to 1) support jsxstyle at both runtime and build-time with 2) an API that doesn’t suck.

The API I’ve been thinking about looks something like this: runtime jsxstyle exports a new stylable component factory function called `createComponent` (name TBD). This function takes an optional single param that is either an object of style props or a function that takes an object of style props, transforms it, and returns a copy. The style object becomes the `defaultProps` for the returned component.

Here’s a contrived example:

```jsx

import { createComponent } from 'jsxstyle';

export const BlueBlock = createComponent({
  display: 'block',
  color: '#FFF',
  backgroundColor: 'blue',
});

export const Container = createComponent(({ spacing = 0 }) => ({
  padding: spacing,
  margin: spacing,
  borderRadius: spacing / 2,
}));

```

Style objects passed to `createComponent` would need to be able to be statically analysed. The one thing I’m not sure about is how to indicate to the. Best option I can think of right now would be to require users of `jsxstyle-webpack-plugin` to provide the path(s) to the file(s) that contain custom jsxstyle components, similar to the `whitelistedModules` option. `componentModules` perhaps? Not sure.

**Comment by ex3ndr** [comment]
I would prefer actually separate library, this is a very common task actually - to extract some static information from components and mangle props.

For marking such preprocessors we can try to use directives in our compile pipeline that will mark components that need to be processed with specific pre-registered preprocessor.

**Comment by meyer** [comment]
@ex3ndr ah, I see what you mean. Since refactoring style extraction is not super high on the priority list at the moment and since it’ll take quite a bit of work to convert the style extraction/mangling code into a reusable library, this won’t be something I’ll be able to get to in the neat future. It is a good idea, however, and if you’d like to lead the charge on converting [`extractStyles.ts`](https://github.com/jsxstyle/jsxstyle/blob/76397c7/packages/jsxstyle-webpack-plugin/src/utils/ast/extractStyles.ts) into a reusable library, I would be available to review any code or provide input if you need it.

Regarding using a directive to mark a component as needing mangling, that should be simple enough to do with a babel plugin. [`babel-plugin-sitrep`](https://github.com/tkh44/babel-plugin-sitrep) does something similar with specially-formatted comments. This features is not something I’m looking to add to jsxstyle at the moment however.
