### ISSUE TITLE
Break with  typescript's generic component

### ISSUE THREAD

**Issue by Sunshine168** [jsxstyle/jsxstyle#130]
Provider a simple example 

```
function Form<T>(items: T[]) {
  return <Select<T> items={items} />;
}
```

error message 

```
SyntaxError: Unexpected token
```

**Comment by meyer** [comment]
@Sunshine168 I suspect it’s a babel 7 issue. Investigating…

**Comment by meyer** [comment]
@Sunshine168 ooh, I’ll take a look now. I have a few initial questions for you:

- Can you provide me with more information about your environment? Version numbers of jsxstyle and TypeScript would be super helpful.
- Are you using jsxstyle on its own, or are you using jsxstyle with `jsxstyle-webpack-plugin`?
- Did you just add jsxstyle to this project, or have you been using jsxstyle with this project for a while?

Thanks!

**Comment by Sunshine168** [comment]
@meyer Hello
 Version:
```
"jsxstyle": "^2.1.3,
"jsxstyle-webpack-plugin": "^1.1.3",
"typescript": "^3.0.1",
```

We use jsxstyle with jsxstyle-webpack-plugin and using jsxstyle with this project for a long time

**Comment by meyer** [comment]
Thanks for the info, @Sunshine168. Reproducing this bug was quite easy—looks like an issue on the babel side of things. I’m looking at switching the parser to use `typescript-estree` instead of `@babel/parser`, which would give us support for any new TypeScript features that might come along (including JSX type parameters). I’ll keep you updated here as I make progress on the switch.

**Comment by meyer** [comment]
@Sunshine168 I haven’t had a lot of time to work on switching the parser to `typescript-estree`. I did realise yesterday that this issue has already come up and has a solution:

It’s not ideal, but basically `babel-loader` needs to run in addition to `ts-loader`. Here’s how things need to be configured:
- `JsxstyleWebpackPlugin.loader` should run _after_ `ts-loader` ([see example](https://github.com/jsxstyle/jsxstyle/blob/0b313bd/examples/jsxstyle-typescript-example/webpack.config.ts#L56-L74))
- `compilerOptions.jsx` should be set to `"preserve"` in your tsconfig ([see example](https://github.com/jsxstyle/jsxstyle/blob/0b313bd/examples/jsxstyle-typescript-example/tsconfig.json#L5))
- `babel-loader` should run after `JsxstyleWebpackPlugin.loader` to transpile JSX ([see example](https://github.com/jsxstyle/jsxstyle/blob/0b313bd/examples/jsxstyle-typescript-example/webpack.config.ts#L30-L45))

Since `jsxstyle-webpack-plugin` is already parsing JSX, I can look into adding a `transpileJsx` option so that the `babel-loader` portion can be skipped.

Let me know if that works for you, or if you have a better solution.
