### ISSUE TITLE
Question about useMatchMedia

### ISSUE THREAD

**Issue by chenxsan** [jsxstyle/jsxstyle#145]
I'm trying `useMatchMedia` in my project and I found myself having to write rules more explicitly, e.g.:

```jsx
// const tablet = useTablet() <- custom hook

<Col
        flexDirection={tablet ? 'row' : 'column'}
        width={tablet ? 896 : 'auto'}
        marginLeft="auto"
        marginRight="auto"
      >
</Col>
```
Now I have to write `'column'` even `Col` is there, also I can't fallback to any default value browser has for `width` but to write `auto` in my code.

Considering more complex cases, if i have to change `flexDirection` for 4 breakpoints all the time, i would have to write something like `tablet ? 'row' : (desktop ? 'column' : (tv ? 'row' : 'column'))` which is kind of messy now.

Do you have any suggestions for such use cases?

**Comment by meyer** [comment]
@chenxsan hey there, sorry for the super delayed reply.

For the fallback case, I’d recommend using the `&&` operator:

```jsx
<Col width={tablet && 896} />
```

The `false` case here will simply result in no `width` property being set, since `false`, `null`, and `undefined` are all automatically removed from the generated styles. This would allow this style prop to fall back to the either the default value or your globally overridden value.

For changing one prop between two values, I recommend something like the following:

```jsx
const isTablet = useMatchMedia('screen and your-tablet-media-query');
const isTV = useMatchMedia('screen and your-tv-media-query');

const shouldDisplayAsRow = isTablet || isTV;

return <Col flexDirection={shouldDisplayAsRow ? 'row' : 'column'} />;
```

This is assuming, of course, that your media queries are mutually exclusive.

This is a case where I think the deprecated `Flex` component could be used. I’m considering undeprecating the component for cases like this.

For cases where you’re setting a different value for each breakpoint: yeah, it can start to get messy. I don’t know of a compact solution to this problem. I haven’t really run into it in my own code, but it’s mainly because i lean pretty heavily on flex items handling their own dimensions given a reasonable flex-basis. Usually I’m only tweaking two or three props with a media query.

**Comment by meyer** [comment]
Closing for now. Feel free to reopen if you have any more questions!
