### ISSUE TITLE
Color helpers

### ISSUE THREAD

**Issue by petehunt** [jsxstyle/jsxstyle#149]
Made a little color helper, it's pretty useful when you have a color palette

```
class ColorObj extends String {
  private readonly r: number;
  private readonly g: number;
  private readonly b: number;
  private readonly a: number;

  constructor(r: number, g: number, b: number, a: number = 1) {
    if (a === 1) {
      super(`rgb(${r}, ${g}, ${b})`);
    } else {
      super(`rgba(${r}, ${g}, ${b}, ${a})`);
    }

    this.r = r;
    this.g = g;
    this.b = b;
    this.a = a;
  }

  alpha(a: number): Color {
    return new ColorObj(this.r, this.g, this.b, this.a * a) as Color;
  }
}

export type Color = ColorObj & string;

export function rgba(r: number, g: number, b: number, a: number = 1): Color {
  return new ColorObj(r, g, b, a) as Color;
}
```

**Comment by meyer** [comment]
There are a number of JS color libraries out there that provide functionality ranging from color creation all the way to advanced color manipulation (blending modes, darken/lighten, interpolating between colors, etc.). Unless we’re doing something jsxstyle-specific with color helpers, I’d rather point folks to an existing color library rather than start maintaining one. Any color object that stringifies to a valid CSS color is compatible with jsxstyle (might be a good idea to point that out in the README).

I’m going to close this for now, but if there’s something jsxstyle-specific you were thinking of doing, feel free to reopen. I’m very much into the idea of providing useful utilities in jsxstyle.
